apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: lab-kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 4
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: persistent-claim
      class: local-path
      size: 100Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 200m
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: local-path
      size: 10Gi
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 100m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 400Mi
          cpu: 50m
        limits:
          memory: 400Mi
          cpu: 50m
    userOperator:
      resources:
        requests:
          memory: 400Mi
          cpu: 50m
        limits:
          memory: 400Mi
          cpu: 50m
  cruiseControl:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 100m