apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
  namespace: lab-kafka
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: -1  # -1 (forever) instead of 604800000 (7 days)
    segment.bytes: 107374182 # 100Mi instead of 1Gi
#    cleanup.policy: compact
